server.port=8075

# SQLite
spring.datasource.url=jdbc:sqlite:./glpi-data.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Dates ISO 8601 dans les réponses JSON
spring.jackson.serialization.write-dates-as-timestamps=false
